version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=App4ever#
      - DB_NAME=time_app_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=App4ever#
      - POSTGRES_DB=time_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
