apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.clusterRoleBinding.serviceAccount.name }}
    namespace: {{ .Values.clusterRoleBinding.serviceAccount.namespace }}
roleRef:
  kind: {{ .Values.clusterRoleBinding.roleRef.kind }}
  name: {{ .Values.clusterRoleBinding.roleRef.name }}
  apiGroup: {{ .Values.clusterRoleBinding.roleRef.apiGroup }}
