apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-application
  annotations:
    "kubernetes.io/ingress.class": {{ .Values.ingress.nginxIngressClass }}
    "nginx.ingress.kubernetes.io/rewrite-target": {{ .Values.ingress.rewriteTarget }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.ingress.serviceName }}
                port:
                  number: {{ .Values.ingress.servicePort }}
