apiVersion: v1
kind: Service
metadata:
  name: nginx-flask-service
spec:
  selector:
    app: nginx-flask
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: flask-port
      protocol: TCP
      port: 5000
      targetPort: 5000
